// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

// Load .env.local for local development
config({ path: '.env.local' })

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx dotenv -e .env.local -- tsx prisma/seed.ts',
  },
  datasource: {
    // Use DIRECT_URL for CLI operations (migrations, db push)
    // Runtime Prisma Client uses DATABASE_URL from environment
    url: process.env['DIRECT_URL'] || process.env['DATABASE_URL'],
  },
})
